### ISSUE TITLE
Find a home to deploy the API

### ISSUE THREAD

**Issue by benhylau** [starlinglab/starling-integrity-api#1]
## Task Summary

📅 **Due date:** 23 Nov 2021  
🎯 **Success criteria:** Have the Python API in this repo hosted on a public endpoint I can POST files to.  

## To Do

- [x] Decide were to put it
- [x] Create a functioning environment
  - [x] install and run api server as server
  - [x] Get a hostname
  - [x] nginx for SSL
- [x] Define location for files
- [x] Final resting place of API

**Comment by anaulin** [comment]
All the tasks at the top of this ticket are marked as done. @benhylau @YurkoWasHere can this entire ticket be closed, or are we still working on some additional tasks?
