### ISSUE TITLE
Build an API to receive files and output C2PA-injected images

### ISSUE THREAD

**Issue by benhylau** [starlinglab/starling-integrity-api#2]
## Task Summary

📅 **Due date:** 24 Nov 2021  
🎯 **Success criteria:** Build an API that allows backend to receive [ photos + JSON ] and inject C2PA with capture signatures in Capture assertion.  

Links you'll need:
- `claim-tool` binary and docs: https://github.com/starlinglab/organizing-private/issues/14#issuecomment-973704015
- C2PA v0.8 verifier: https://verify.contentauthenticity.org/inspect
- C2PA v0.8 spec: https://c2pa.org/public-draft/
- Starling App (Android-only): https://www.dropbox.com/sh/23twqukw4mlk0lv/AACesyMPrH5cLtyEwXDesqcwa?dl=0
  - This is a dev build from @benhylau (same one used by Pablo)
  - @benhylau will document data format in #3 
- Numbers Data Integrity Assurance (DIA) API v3: https://dia-backend.numbersprotocol.io/api/v3/redoc/
  - This is what Starling Capture app currently talks to
- The master issue for SCMP coordination: https://github.com/starlinglab/organizing-private/issues/22

## To Do

- [x] @benhylau to provide Starling Capture test files
- [ ] spec API to receive and fetch
- [x] add basic auth
- [x] implement APIs in Python
- [x] @benhylau to provide claim format for Capture assertion injection
- [x] do an injection thru `claim-tool`
- [ ] verify sending source files via POST and fetching C2PA-injected images thru GET
  - 🤔 how we (e.g. SCMP) list directories?

**Comment by benhylau** [comment]
I think we built the APIs for the job at the time. Future APIs can be scoped in new tickets. Closing!
