### ISSUE TITLE
Publishing to IPFS and Filecoin

### ISSUE THREAD

**Issue by benhylau** [starlinglab/starling-integrity-api#4]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Publish a bunch of cat photos to IPFS nad Filecoin and get back the IPFS CID and Filecoin Piece CID.  

I put a folder of openly licenses cat photos onto SCMP's FTP. Please investigate how best to publish them onto IPFS and Filecoin and receive the IPFS CID and a permanent identifier to discover the asset on the Filecoin network (I think the Piece CID).

@YurkoWasHere pls see [this giant thread](https://starlinglab.slack.com/archives/C01P8ASDX38/p1637281693036900) for context on Filecoin identifiers.

From that thread, here are some key messages:

>You can use any service to upload + pin the file to IPFS first (without the Filecoin incentive layer) for immediate upload + access to the file. Afterwards, you need to upload that file to a Filecoin storage provider through a storage client proxy (via Estuary, Web3.storage, PiKNiK (coming soon), etc).
One thing to note: the CID of a file can be different depending on the hashing algorithm & CID version used in generation, so you have to make sure the storage client proxy uses the same method of CID generation as the IPFS pinning service used.

>Yep, I agree. Using the Piece CID is the way to go for embedding into the image asset, which will allow the reference on blockchain explorers. However, I think you should also include the data CID (the IPFS CID) as well since that’s how the data will actually be retrieved.

>storing data in filecoin on your own will not result in it being retrievable on the ipfs network, you need something like estuary to provide that service

>With the technology right now, you would need to make a new CAR (if you don’t already have the previous CAR saved), and resubmit that deal. Estuary may have something to make renewals easier. The Piece CID can remain unchanged using the same params.

Note that:
- The Piece CID is not what's used in [78 days](https://www.starlinglab.org/78daysarchive/)
- There isn't a way to map IPFS CID to Filecoin Piece ID, other than some local black magic that some people do (what Why described in the thread, I wouldn't use that in our design)
- In Filecoin ecosystems, the IPFS CID is sometimes referred to as _Payload CID_ or _Data CID_
- We want to avoid running IPFS and Filecoin internally, and rely on client proxy services

Our requirements for the stored asset:
- Retrievable from the IPFS network
- Link to a stable ID on the Filecoin network such that active and future deals associated with same content can be retrieved
- Does not take > 10 minutes to produce

## To Do

- [x] Confirm that IPFS CID and Filecoin Piece CID is the two identifier we want to store in the C2PA manifest (@benhylau thinks so)
  - Read: https://filecoin.io/blog/posts/how-storage-and-retrieval-deals-work-on-filecoin/
    - Could we end up with multiple Piece CIDs for one large asset (e.g. video)?
      >The Filecoin Piece is the main unit of negotiation for data that users store on the Filecoin network. The Filecoin Piece is not of a specific size, but is upper-bounded by the size of the Sector, governed by the parameters of the network. If a Filecoin Piece is larger than the size of a Sector that the miner supports, it has to be split into more pieces so that each piece fits into a sector.
- [x] Investigate IPFS and Filecoin _client proxies_ listed here https://github.com/starlinglab/organizing-private/issues/2
  - Web3.Storage (see: https://docs.web3.storage/how-tos/list/#listing-your-uploads)
  - Estuary
  - Textile
- [x] Publish the cat photos 🐈
- [x] Ping @benhylau to use the returned identifiers for C2PA injection 🚀

**Comment by benhylau** [comment]
The backend now publishes. We need to add more features like polling web3.storage for Piece CID when available then do injection. Spinning out a new ticket.
